"""add created date to conversion table

Revision ID: 022007d78798
Revises: aa29fd27a12d
Create Date: 2025-12-30 09:27:07.400709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '022007d78798'
down_revision: Union[str, Sequence[str], None] = 'aa29fd27a12d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_uom_conversions', sa.Column('created_date', sa.DateTime(), nullable=False), schema='main')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_uom_conversions', 'created_date', schema='main')
    # ### end Alembic commands ###
