"""add sup id in item

Revision ID: 1188c7623fb5
Revises: 4e51764951d7
Create Date: 2026-04-06 10:57:11.984439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1188c7623fb5'
down_revision: Union[str, Sequence[str], None] = '4e51764951d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('supplier_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False), schema='main')
    op.create_foreign_key(None, 'items', 'suppliers', ['supplier_id'], ['id'], source_schema='main', referent_schema='main')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'items', schema='main', type_='foreignkey')
    op.drop_column('items', 'supplier_id', schema='main')
    # ### end Alembic commands ###
