"""journal tbl update

Revision ID: 1e760f6d2ec0
Revises: dc8ebc26370f
Create Date: 2026-03-31 08:32:37.529469

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "1e760f6d2ec0"
down_revision: Union[str, Sequence[str], None] = "dc8ebc26370f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "accounts",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("code", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("modified_date", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="main",
    )
    op.create_index(
        op.f("ix_main_accounts_code"), "accounts", ["code"], unique=True, schema="main"
    )
    op.create_table(
        "journal_entries",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("reference_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("reference_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("modified_date", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        schema="main",
    )
    op.create_index(
        op.f("ix_main_journal_entries_id"),
        "journal_entries",
        ["id"],
        unique=False,
        schema="main",
    )
    op.create_table(
        "journal_entry_lines",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "journal_entry_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("account_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("debit", sa.Float(), nullable=False),
        sa.Column("credit", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["main.accounts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"],
            ["main.journal_entries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="main",
    )
    op.create_index(
        op.f("ix_main_journal_entry_lines_id"),
        "journal_entry_lines",
        ["id"],
        unique=False,
        schema="main",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "journal_entry_lines",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "journal_entry_id", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column("account_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "debit",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "credit",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["accounts.id"],
            name=op.f("journal_entry_lines_account_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["journal_entry_id"],
            ["journal_entries.id"],
            name=op.f("journal_entry_lines_journal_entry_id_fkey"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("journal_entry_lines_pkey")),
    )
    op.create_table(
        "accounts",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("code", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("active", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "modified_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("accounts_pkey")),
    )
    op.create_index(op.f("ix_accounts_code"), "accounts", ["code"], unique=True)
    op.create_table(
        "journal_entries",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("date", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("reference_type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("reference_id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("description", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("journal_entries_pkey")),
    )
    # ### end Alembic commands ###
