"""remove account data from emp table

Revision ID: 294fc220c563
Revises: 53df0b7a2a5c
Create Date: 2025-09-17 15:09:19.014279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '294fc220c563'
down_revision: Union[str, Sequence[str], None] = '53df0b7a2a5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('employees_email_key'), 'employees', schema='main', type_='unique')
    op.drop_constraint(op.f('employees_username_key'), 'employees', schema='main', type_='unique')
    op.drop_column('employees', 'email', schema='main')
    op.drop_column('employees', 'password', schema='main')
    op.drop_column('employees', 'username', schema='main')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=False), schema='main')
    op.add_column('employees', sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False), schema='main')
    op.add_column('employees', sa.Column('email', sa.VARCHAR(length=100), autoincrement=False, nullable=False), schema='main')
    op.create_unique_constraint(op.f('employees_username_key'), 'employees', ['username'], schema='main', postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('employees_email_key'), 'employees', ['email'], schema='main', postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
