"""alter menu table name into title

Revision ID: 31f62db5636a
Revises: 4da9131b2fad
Create Date: 2025-10-17 05:58:27.450298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '31f62db5636a'
down_revision: Union[str, Sequence[str], None] = '4da9131b2fad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menu', 'name', new_column_name='title', schema='admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('menu', 'title', new_column_name='name', schema='admin')
    # ### end Alembic commands ###
