"""init db

Revision ID: 3301441b4e81
Revises: 
Create Date: 2025-09-11 06:41:00.181075

"""
from typing import Sequence, Union

from alembic import op

import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3301441b4e81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_index(op.f('ix_main_departments_id'), 'departments', ['id'], unique=False, schema='main')
    op.create_table('employees',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('position_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('department_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('hire_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modified_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_index(op.f('ix_main_employees_id'), 'employees', ['id'], unique=False, schema='main')
    op.create_table('positions',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('reports_to_pos_id', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_index(op.f('ix_main_positions_id'), 'positions', ['id'], unique=False, schema='main')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_main_positions_id'), table_name='positions', schema='main')
    op.drop_table('positions', schema='main')
    op.drop_index(op.f('ix_main_employees_id'), table_name='employees', schema='main')
    op.drop_table('employees', schema='main')
    op.drop_index(op.f('ix_main_departments_id'), table_name='departments', schema='main')
    op.drop_table('departments', schema='main')
    # ### end Alembic commands ###
