"""migrate invoice tbl

Revision ID: 4e51764951d7
Revises: 1e760f6d2ec0
Create Date: 2026-03-31 08:38:31.801737

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "4e51764951d7"
down_revision: Union[str, Sequence[str], None] = "1e760f6d2ec0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "invoices",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("invoice_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("delivery_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("customer_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("total_amount", sa.Float(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["main.customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["delivery_id"],
            ["main.deliveries.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="main",
    )
    op.create_index(
        op.f("ix_main_invoices_invoice_number"),
        "invoices",
        ["invoice_number"],
        unique=True,
        schema="main",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_main_invoices_invoice_number"), table_name="invoices", schema="main"
    )
    op.drop_table("invoices", schema="main")
    # ### end Alembic commands ###
