"""change dept id to manager id emp table

Revision ID: 53df0b7a2a5c
Revises: 984817fce63d
Create Date: 2025-09-17 14:03:34.527654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '53df0b7a2a5c'
down_revision: Union[str, Sequence[str], None] = '984817fce63d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('manager_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True), schema='main')
    op.create_foreign_key(None, 'employees', 'positions', ['position_id'], ['id'], source_schema='main', referent_schema='main', ondelete='CASCADE')
    op.drop_column('employees', 'department_id', schema='main')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('department_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False), schema='main')
    op.drop_constraint(None, 'employees', schema='main', type_='foreignkey')
    op.drop_column('employees', 'manager_id', schema='main')
    # ### end Alembic commands ###
