"""add relation dept pos table

Revision ID: 5c164440e20c
Revises: d8dc91f2f8dc
Create Date: 2025-09-16 15:01:25.257829

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5c164440e20c'
down_revision: Union[str, Sequence[str], None] = 'd8dc91f2f8dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("""
    CREATE TYPE positionlevel AS ENUM (
        'Intern',
        'Junior',
        'Mid',
        'Senior',
        'Lead',
        'Manager',
        'Director',
        'VP',
        'C-Level'
        )
    """)
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('level', sa.Enum('INTERN', 'JUNIOR', 'MID', 'SENIOR', 'LEAD', 'MANAGER', 'DIRECTOR', 'VP', 'C_LEVEL', name='positionlevel'), nullable=False), schema='main')
    op.add_column('positions', sa.Column('department_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False), schema='main')
    op.create_foreign_key(None, 'positions', 'departments', ['department_id'], ['id'], source_schema='main', referent_schema='main', ondelete='CASCADE')
    op.drop_column('positions', 'reports_to_pos_id', schema='main')
    # ### end Alembic commands ###


def downgrade() -> None:
    op.execute("DROP TYPE IF EXISTS positionlevel")
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('reports_to_pos_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True), schema='main')
    op.drop_constraint(None, 'positions', schema='main', type_='foreignkey')
    op.drop_column('positions', 'department_id', schema='main')
    op.drop_column('positions', 'level', schema='main')
    # ### end Alembic commands ###
