"""sync alembic

Revision ID: 5dd47218942b
Revises: c4799188e6d4
Create Date: 2025-12-24 15:54:09.236212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5dd47218942b'
down_revision: Union[str, Sequence[str], None] = 'c4799188e6d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_main_stock_balances_id'), table_name='stock_balances', schema='main')
    op.drop_table('stock_balances', schema='main')
    op.drop_index(op.f('ix_main_stock_movements_id'), table_name='stock_movements', schema='main')
    op.drop_table('stock_movements', schema='main')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_movements',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('uom_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('ref', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['main.items.id'], name=op.f('stock_movements_item_id_fkey')),
    sa.ForeignKeyConstraint(['uom_id'], ['main.unit_of_measure.id'], name=op.f('stock_movements_uom_id_fkey')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['main.warehouses.id'], name=op.f('stock_movements_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_movements_pkey')),
    schema='main'
    )
    op.create_index(op.f('ix_main_stock_movements_id'), 'stock_movements', ['id'], unique=False, schema='main')
    op.create_table('stock_balances',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('item_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('warehouse_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('qty', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qty_reserved', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('qty_available', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('modified_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['main.items.id'], name=op.f('stock_balances_item_id_fkey')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['main.warehouses.id'], name=op.f('stock_balances_warehouse_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_balances_pkey')),
    schema='main'
    )
    op.create_index(op.f('ix_main_stock_balances_id'), 'stock_balances', ['id'], unique=False, schema='main')
    # ### end Alembic commands ###
