"""add emp status

Revision ID: 66fe10a20e96
Revises: 3301441b4e81
Create Date: 2025-09-11 22:11:27.866886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '66fe10a20e96'
down_revision: Union[str, Sequence[str], None] = '3301441b4e81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False), schema='main')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'status', schema='main')
    # ### end Alembic commands ###
