"""upd mod. date dept & emp. table

Revision ID: 6b350edb4ee9
Revises: c242a275a464
Create Date: 2025-09-15 13:31:12.534556

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b350edb4ee9'
down_revision: Union[str, Sequence[str], None] = 'c242a275a464'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('modified_date', sa.Date(), nullable=False), schema='main')
    op.alter_column('employees', 'hire_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=False,
               schema='main',
               postgresql_using='hire_date::date')
    op.alter_column('employees', 'modified_date',
               existing_type=sa.VARCHAR(),
               type_=sa.DateTime(),
               existing_nullable=False,
               schema='main',
               postgresql_using='modified_date::timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employees', 'modified_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               schema='main',
               postgresql_using='modified_date::varchar')
    op.alter_column('employees', 'hire_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=False,
               schema='main',
               postgresql_using='hire_date::varchar')
    op.drop_column('departments', 'modified_date', schema='main')
    # ### end Alembic commands ###
