"""drop level col pos table

Revision ID: 984817fce63d
Revises: 5c164440e20c
Create Date: 2025-09-16 15:56:17.254403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '984817fce63d'
down_revision: Union[str, Sequence[str], None] = '5c164440e20c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'level', schema='main')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('level', postgresql.ENUM('Intern', 'Junior', 'Mid', 'Senior', 'Lead', 'Manager', 'Director', 'VP', 'C-Level', name='positionlevel'), autoincrement=False, nullable=False), schema='main')
    # ### end Alembic commands ###
