"""upd mod. date dept table

Revision ID: 9b532148a4ad
Revises: 6b350edb4ee9
Create Date: 2025-09-15 15:00:23.365586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b532148a4ad'
down_revision: Union[str, Sequence[str], None] = '6b350edb4ee9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'modified_date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               existing_nullable=False,
               schema='main',
               postgresql_using='modified_date::timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('departments', 'modified_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               existing_nullable=False,
               schema='main',
               postgresql_using='modified_date::varchar')
    # ### end Alembic commands ###
