"""add stock bal. constraint & del qty avail.

Revision ID: aa29fd27a12d
Revises: 5dd47218942b
Create Date: 2025-12-29 10:55:04.847996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa29fd27a12d'
down_revision: Union[str, Sequence[str], None] = '5dd47218942b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('unique_item_warehouse', 'stock_balances', ['item_id', 'warehouse_id'], schema='main')
    op.drop_column('stock_balances', 'qty_available', schema='main')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock_balances', sa.Column('qty_available', sa.INTEGER(), autoincrement=False, nullable=False), schema='main')
    op.drop_constraint('unique_item_warehouse', 'stock_balances', schema='main', type_='unique')
    # ### end Alembic commands ###
