"""default active for create uom conversion

Revision ID: af3a691d9346
Revises: 022007d78798
Create Date: 2025-12-30 14:12:07.206084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af3a691d9346'
down_revision: Union[str, Sequence[str], None] = '022007d78798'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item_uom_conversions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               schema='main')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('item_uom_conversions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               schema='main')
    # ### end Alembic commands ###
