"""add cust & sales order table

Revision ID: c02bacc5da09
Revises: af3a691d9346
Create Date: 2026-03-29 04:03:26.794868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c02bacc5da09'
down_revision: Union[str, Sequence[str], None] = 'af3a691d9346'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=15), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='main'
    )
    op.create_index(op.f('ix_main_customers_id'), 'customers', ['id'], unique=False, schema='main')
    op.create_table('sales_orders',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('so_number', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('customer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('warehouse_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('modified_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['main.customers.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['main.warehouses.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('so_number'),
    schema='main'
    )
    op.create_index(op.f('ix_main_sales_orders_id'), 'sales_orders', ['id'], unique=False, schema='main')
    op.create_table('sales_order_lines',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('so_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('item_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uom_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('qty_ordered', sa.Float(), nullable=False),
    sa.Column('qty_delivered', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['main.items.id'], ),
    sa.ForeignKeyConstraint(['so_id'], ['main.sales_orders.id'], ),
    sa.ForeignKeyConstraint(['uom_id'], ['main.unit_of_measure.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='main'
    )
    op.create_index(op.f('ix_main_sales_order_lines_id'), 'sales_order_lines', ['id'], unique=False, schema='main')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_main_sales_order_lines_id'), table_name='sales_order_lines', schema='main')
    op.drop_table('sales_order_lines', schema='main')
    op.drop_index(op.f('ix_main_sales_orders_id'), table_name='sales_orders', schema='main')
    op.drop_table('sales_orders', schema='main')
    op.drop_index(op.f('ix_main_customers_id'), table_name='customers', schema='main')
    op.drop_table('customers', schema='main')
    # ### end Alembic commands ###
