"""add cols emp table

Revision ID: c242a275a464
Revises: 66fe10a20e96
Create Date: 2025-09-12 16:48:32.335713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c242a275a464'
down_revision: Union[str, Sequence[str], None] = '66fe10a20e96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False), schema='main')
    op.add_column('employees', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False), schema='main')
    op.add_column('employees', sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False), schema='main')
    op.create_unique_constraint(None, 'employees', ['username'], schema='main')
    op.create_unique_constraint(None, 'employees', ['email'], schema='main')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'employees', schema='main', type_='unique')
    op.drop_constraint(None, 'employees', schema='main', type_='unique')
    op.drop_column('employees', 'password', schema='main')
    op.drop_column('employees', 'username', schema='main')
    op.drop_column('employees', 'email', schema='main')
    # ### end Alembic commands ###
