"""add mod. date pos table

Revision ID: d8dc91f2f8dc
Revises: 9b532148a4ad
Create Date: 2025-09-16 01:37:23.718693

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8dc91f2f8dc'
down_revision: Union[str, Sequence[str], None] = '9b532148a4ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('positions', sa.Column('modified_date', sa.DateTime(), nullable=False), schema='main')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('positions', 'modified_date', schema='main')
    # ### end Alembic commands ###
