"""update account tbl

Revision ID: dc8ebc26370f
Revises: 574b3ec306e3
Create Date: 2026-03-30 09:49:35.373896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc8ebc26370f'
down_revision: Union[str, Sequence[str], None] = '574b3ec306e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('modified_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'modified_date')
    # ### end Alembic commands ###
