from fastapi import APIRouter, Depends
from sqlmodel import Session as SessionType

from src.core.schemas.inventory.item import Item
from src.core.settings.database import get_session

from .dependency import validate_stock_movement
from .service import get_all, get_by_id, create


router = APIRouter(prefix="/stock_movement", tags=["Stock Movements"])


@router.get("/")
def get_all_stock_movements(session=Depends(get_session)):
    stock_movements = get_all(session)
    return stock_movements


@router.get("/{id}")
def get_stock_movement(id: str, session=Depends(get_session)):
    stock_movement = get_by_id(id, session)
    return stock_movement


# Temporary for testing. Later the data will be autogenerated from other features.
@router.post("/")
def create_item(data: Item, session: SessionType = Depends(get_session)):
    validated_stock_movement = validate_stock_movement(data, session)
    return create(validated_stock_movement, session)